### ISSUE TITLE
Typescript: listen property does not exist on type 'Presence Channel'

### ISSUE THREAD

**Issue by willypuzzle** [laravel/echo#239] opened 2019-08-06 12:54 UTC
I use laravel echo with Typescript and I have a problem on listen property, I receive a 

> TS2339: Property 'listen' does not exist on type 'PresenceChannel'.

In this segment of code:

```
    echo.join(channel)
            .here((users) => {
                EventBusMain.$emit(EVENTS.HERE_MAIN_CHANNEL_EVENT, {users});
            })
            .joining((user) => {
                EventBusMain.$emit(EVENTS.JOIN_MAIN_CHANNEL_EVENT, {user});
            })
            .leaving((user) => {
                EventBusMain.$emit(EVENTS.LEAVE_MAIN_CHANNEL_EVENT, {user});
            })
            .listen('.event', (e) => {
                EventBusMain.$emit(e.event, e.data)
            });
```

The version of laravel echo I'm using is 1.5.4

**Comment by driesvints** [comment] 2019-08-06 12:55
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by willypuzzle** [comment] 2019-08-06 12:59
I think this is a problem of Echo interface bug of typescript because that property is declared in the [documentation](https://laravel.com/docs/5.8/broadcasting#broadcasting-to-presence-channels) but not declared in the typescript interface. I think this is a bug of typescript.

**Comment by driesvints** [comment] 2019-08-06 13:18
@willypuzzle I actually closed it because I didn't saw an issue template. If you're reporting bugs please fill it out next time.

I indeed don't see the `listen` method on the PresenceChannel interface but it is defined as an abstract method. So not sure why Typescript is complaining. If the return type has it defined. Maybe I don't understand Typescript well enough. Which connector are you using?

**Comment by willypuzzle** [comment] 2019-08-06 13:23
I'm using typescript version 2.9.2

**Comment by driesvints** [comment] 2019-08-06 13:27
I meant pusher or socket.io

**Comment by willypuzzle** [comment] 2019-08-06 13:28
pusher-js@4.4.0

**Comment by willypuzzle** [comment] 2019-08-06 14:20
However this is a bug, please could you open it?

**Comment by driesvints** [comment] 2019-08-06 17:42
Is anything broken? It feels there's just a typescript warning here and not a bug.

**Comment by Mathem8tic** [comment] 2019-08-14 17:39
When trying to build with Angular CLI it creates an error not a warning, preventing the build.
`ERROR in [file]: error TS2339: Property 'listen' does not exist on type 'PresenceChannel'.`

**Comment by driesvints** [comment] 2019-08-15 09:47
Okay we'll have a second look at this. Appreciating a PR if you can send one in.

**Comment by driesvints** [comment] 2019-08-15 09:48
What would really help for me to reproduce this is a test repo which reproduces the issue or at least your build script and instructions on how to run it.

**Comment by Mathem8tic** [comment] 2019-08-21 17:10
@driesvints PR created.  

Below is a quick example of an Angular setup that would throw the error.  Only the listen method seems to cause the issue:

`
this.echo.join('Viewing'.' + this.item.id)
.here((members) => {})
.joining((joiningMember) => {})
.leaving((leavingMember) => {})
.listen('EditingEvent', (editor) => {})
`

**Comment by Mathem8tic** [comment] 2019-08-21 17:41
@driesvints Reproduced in repo [echoTest](https://github.com/Mathem8tic/echoTest)

Try running: `ng build --prod`

**Comment by mengyang1229** [comment] 2019-11-06 02:33
@willypuzzle @driesvints @Mathem8tic @ellisio @JeffreyWay 

I found a solution that worked for me and hope it can help you.

`import { NullPresenceChannel } from 'laravel-echo/src/channel'`

```
const LaravelEchoChannel = echo.join(channel)
    .here((users) => {
        EventBusMain.$emit(EVENTS.HERE_MAIN_CHANNEL_EVENT, {users});
    })
    .joining((user) => {
        EventBusMain.$emit(EVENTS.JOIN_MAIN_CHANNEL_EVENT, {user});
    })
    .leaving((user) => {
        EventBusMain.$emit(EVENTS.LEAVE_MAIN_CHANNEL_EVENT, {user});
    }) as NullPresenceChannel;

LaravelEchoChannel
    .listen('.event', (e) => {
        EventBusMain.$emit(e.event, e.data)
    });

```

**Comment by driesvints** [comment] 2020-04-20 13:09
I'm going to close this because I feel that there isn't much progress here to make anymore. All the types seem to be defined properly on all channel classes so I wouldn't know how this problem could exist. The solution from https://github.com/laravel/echo/pull/241 also doesn't seems to be wanted because we don't want the listen method to be defined on the presence channels interface. 

Anyone's free to send in a PR and explain in detail why it would be needed, thanks.

**Closed by driesvints** 2020-04-20 13:09 UTC
Labels: bug

**Comment by johnpaulmedina** [comment] 2020-09-09 23:42
So I found that there isn't a bug or an issue with the interface at all with the PresenceChannel.

Just assign <any> as the type for your LaravelEchoChannel ng-cli wont throw any errors.
```es6
  private echo: Echo;
  private LaravelEchoChannel: any;

  LaravelEchoChannel = echo.join(channel)
     .here((users: any) => {
       log.debug('[Presence][Channel]', users);
     })
     .joining((user: any) => {
       log.debug('joining', user.name);
     })
     .leaving((user: any) => {
       log.debug('leaving', user.name);
     });

  LaravelEchoChannel
    .listen('.event', (event: string) => {
       log.debug('event');
    });

```

**Comment by joseacalwobiz** [comment] 2020-09-11 04:39
Error also with vue, typescript and socketio

```
Property 'listen' does not exist on type 'PresenceChannel'.
typescript 3.8.3
laravel-echo 1.8.1
```

**Comment by acaldev** [comment] 2020-09-11 04:40
Error also with vue, typescript and socketio

```
Property 'listen' does not exist on type 'PresenceChannel'.
typescript 3.8.3
laravel-echo 1.8.1
```

**Comment by johnpaulmedina** [comment] 2020-09-11 06:39
You will see this with typescript and other methods like whisper and listenForWhisper. 

You have to define the type of :any on what ever variable you are defining to that PresenceChannel method.

**Comment by acaldev** [comment] 2020-09-12 03:32
I solved in vue defining echo with Echo | any
`

                class SomeCoolClass {

                    echo!: Echo | any
                    
                     presenceChannelMethod(){
                                    this.echo!.join('channel')
                                    .here(variable => {
                                        ... do something
                                    })
                                    .joining(variable => {
                                        ... do something
                                    }).leaving(variable => {
                                        ... do something
                                    }).leaving(variable => {
                                        ... do something
                                    }).listen('SomeEvent', event => {
                                        ... do something
                                    })
                     }
                }`

**Also defining echo with any it's not the right solution to that.**
