### ISSUE TITLE
Updating the Authorization-header

### ISSUE THREAD

**Issue by petervmeijgaard** [laravel/echo#26] opened 2016-08-14 18:10 UTC
So I have a single page application with authorization setup. When the app boots, it will check if the user is authenticated. If not, the user is send to the login page, if so, the app sets the Authorization header of the requests to the token saved in localStorage.
This is working fine, but when I want to login and update the Authorization token, the update isn't reflected and I have to manually refresh the page to make the request with the token.

As you can see here, I set the token correctly:
https://github.com/petervmeijgaard/jwt-example/blob/next/resources/frontend/src/app/store/modules/auth/mutations.js#L24

And even when I do a `console.log(Vue.echo.options.auth.headers.Authorization)` before I subscribe to a private channel, I get the correct token returned.
However, when I check the request send to the REST-server, the Authorization header isn't set.

The `console.log` ouput:
![The console.log output](https://cloud.githubusercontent.com/assets/5537701/17650917/9a97ad80-625a-11e6-9d1f-ed4719536101.png)

The request headers:
![The request headers](https://cloud.githubusercontent.com/assets/5537701/17650918/9a98efc4-625a-11e6-86f5-e5790e65cc94.png)

**Comment by kubacode** [comment] 2016-09-19 05:50
@petervmeijgaard Have you been able to get the Authorisation header set? I'm also running into this issue.

**Comment by petervmeijgaard** [comment] 2016-09-19 08:02
@kubacode Nope, I still haven't figured out how to get it working 😞

**Comment by kubacode** [comment] 2016-09-20 01:43
@petervmeijgaard I think I've figured it out. The Authorization header isn't sent by Echo, its sent by Pusher. Setting the Authorization header in Echo only sets the header when the Pusher instance is constructed.

To set the Authorization header on the fly, you need to set the header on the Pusher object:

```
Echo.connector.pusher.config.auth.headers['Authorization'] = 'Bearer token';
```

I'm using the [vue-auth](https://www.npmjs.com/package/@websanova/vue-auth) plugin, so I'm able to add the header by overriding the _setHeaders function. You should also be able to set the header via a vue-resource interceptor.

**Comment by rgreer4** [comment] 2017-07-09 04:57
Setting the pusher config directly did not work for me (and I'm not using vue-resource) -- but this solution worked:  https://github.com/tlaverdure/laravel-echo-server/issues/129#issuecomment-284216291

In my case I'm, using **vue-echo**, but the config block should work in **Echo** as well.  For example:

`           Vue.use(VueEcho, {
                broadcaster: 'pusher',
                key:         'PUSHER_KEY',
                auth:        {
                    headers: {
                        Authorization: 'Bearer ' + BEARER_TOKEN,
                    },
                },
            });`

...and setting:

`Broadcast::routes(['middleware' => ['auth:api']]);`

...in **BroadcastServiceProvider** as well.

**Comment by a-komarev** [comment] 2017-08-05 21:46
This works for me:

```php
window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: window.location.hostname + ':6001',
    auth: {
        headers: {
            'Authorization': 'Bearer ******'
        }
    }
});
```

**Comment by Krofek** [comment] 2018-03-06 16:06
To set on the fly for socket.io:
Echo.connector.options.auth.headers['Authorization'] = 'Bearer ' + token

**Comment by chimit** [comment] 2018-03-19 07:53
Need a special method in Echo instance to set parameters (at least `headers` and `authEndpoint`) on the fly.

**Comment by a-komarev** [comment] 2018-03-19 09:40
@chimit make a PR then.

**Comment by ibrahimshaer** [comment] 2018-03-28 08:19
Hello, I had the same problem ,and it took me some time to figure it out. I was using pusher as my broadcasting driver. The first step  required changing broadcasting middleware to Broadcast::routes(['middleware' => ['api', 'jwt.auth']]); because I am using jwt authentication. 
This required sending the jwt token from the client-side upon registering to laravel-echo along with changing the authEndpoint as I was using a virtual host. 
The resulting laravel-echo configuration is as follows: 

window.Echo = new Echo({
			broadcaster: 'pusher',
			key: 'PUSHER_KEY',
			authEndpoint :'http://virtual_host/broadcasting/auth', 
			auth: {
				headers: {
					Authorization: 'Bearer ' + CLIENT_TOKEN,
				}
			},
			cluster: 'PUSHER_CLUSTER', 
			encrypted: true
		}); 

I hope my answer will help you.

**Comment by unickortega** [comment] 2018-08-23 01:45
I had the same issue. But mine was 405 method not allowed.
I added added App\Providers\BroadcastServiceProvider::class provider in the config/app.php file.
Then I entered php artisan config cache command.

**Comment by jjoao07** [comment] 2018-10-09 23:31
Hi Guys, 

I'm facing similar issue using Nuxt js, I can't get any events broadcasted on frontend side.

It's have been days so far trying to get it working, i have looked entire googling but nothing is out there envolving laravel-echo with pusher-js using Nuxtjs.

And the funny thing is that I got the same scripts working on the demo side, which I made for testing, using Laravel with Vuejs setup without any API, it works properly.


But now I've created any standalone Nuxtjs project and using Laravel for Backend, and I can't get the events working.

If I check on Pusher Console, I get the broadcast, but nothing is firing on the frontend,

tried all tricks, renaming the Namespace of Echo, using . on Event but nothing works.

Below the code

![image](https://user-images.githubusercontent.com/19816874/46704286-a264ae00-cc2a-11e8-96f2-2168f8153361.png)

Echo Integration

 `import LaravelEcho from "laravel-echo"

export default ({ app, redirect }) => {
    const token = localStorage.getItem('auth._token.local')

    window.Pusher = require('pusher-js');

    window.Echo = new LaravelEcho({
        authEndpoint: `${process.env.apiUrl}accounts/broadcast`,
        broadcaster: 'pusher',
        key: 'mykeysgoeshere',
        cluster: 'eu',
        auth: {
            headers: {
                Authorization: `${token}`
            },
        },
    });
}
`
![image](https://user-images.githubusercontent.com/19816874/46704400-130bca80-cc2b-11e8-9f20-8e1e6d1b41f3.png)

channels.php

![image](https://user-images.githubusercontent.com/19816874/46704423-2e76d580-cc2b-11e8-865f-77d6814219bf.png)

Broadcast route
![image](https://user-images.githubusercontent.com/19816874/46704448-52d2b200-cc2b-11e8-861b-38a3abbce2c7.png)

Broacast call

![image](https://user-images.githubusercontent.com/19816874/46704476-6f6eea00-cc2b-11e8-9b8b-cbb460186adf.png)


Broadcast Provider

![image](https://user-images.githubusercontent.com/19816874/46704490-87466e00-cc2b-11e8-88b9-ef22d996135d.png)

One of the thing which I'm not sure about all of this is how to check broacasting/auth which above I just check if the user is Authenticated or not.

But any help will be appreciated, or any advice if someone tried echo with pusher using Nuxtjs.

**Comment by unr** [comment] 2018-10-16 21:14
Hey @jjoao07, hope I can help you a bit.

I think your biggest issue, is trying to set up a `window.Echo` instance, in your js App. 
Good chance you're calling things too early in the lifecycle to hook up into it properly...

--

Here's an example of how I'm working pusher on my app in nuxt.js. I've set it up as a Vuex Module, so I can easily call it and check instances in my app...

For now, I've dealt with logged in/out states as different echo instances. But I'm working on trying to solve that problem too....

https://gist.github.com/unr/345fe5c9daf7e5daffa1f23842d2c9ab

You can see how I've tried to set up my module, and call it from my main layouts in this gist.

**Comment by jjoao07** [comment] 2018-10-16 21:31
Hi @unr , thanks for your sharing

Will have a look and let u know

**Comment by jjoao07** [comment] 2018-10-24 08:55
Hi @unr 

Sorry for not coming back, I have been trying to get done other stuff in the project, and from yesterday, started working on this again.

I have checked your repo, but  I'm still not getting it in right way. 

I'm getting an error like `Do not mutate vuex store state outside mutation handlers.` while trying to commit the instance to the state, and I have no idea why this happening.

below is what I got

`
import Pusher from 'pusher-js';
import Echo from 'laravel-echo';

const state = () =>({
	private:false,
	public:false
})
 
const actions = {
	createPublic ({commit, state}) {
		return new Promise((resolve, reject) => {
			if( state.public) return resolve(true);
			this.$axios.post('accounts/broadcast')
				.then(() =>{
					const instance = new Echo({
						broadcaster: 'pusher',
						key: process.env.pusherAppKey,
						cluster: process.env.pusherCluster,
						encrypted: true
					})

					commit('setPublic', instance)
					return resolve(true)
				})
				.catch(err => reject(err))
		}) 
	},
	createPrivate ({commit, state}) {
		return new Promise((resolve, reject) =>{
			if( state.private ) return resolve(true);

			this.$axios.post('accounts/broadcast')
				.then(() => {
					const token = localStorage.getItem('auth._token.local')
					const instance = new Echo({
						broadcaster: 'pusher',
						key: process.env.pusherAppKey,
						cluster: process.env.pusherCluster,
						encrypted: true,
						auth: {
							headers: `${token}`
						}
					})
					commit('setPrivate', instance)
					return resolve(true)
				}) 
				.catch(err => reject(err))
		})
	},
	connectToConversationChannel ({dispatch, getters, state}) {
		dispatch('createPrivate').then(() => {
			state.private.private(`conversation.${this.user.uuid}`)
				.listen('ConversationReplyCreated', (e) => {
					console.log(e)
				})
		})
			.catch(err => console.log(err))
	}

}

const mutations = {
	setPublic (state, instance) {
		state.public = instance
	},
	setPrivate (state, instance) {
		state.private = instance
	}
}

const getters = {
	getPublic (state) {
		return state.public
	},
	getPrivate (state) {
		return state.private
	}
}

export default {
	actions,
	mutations,
	getters,
	state
}
And I'm dispatching this like this `this.$store.dispatch('echoModule/createPrivate')`

So not sure what I'm missing out in order to get `Do not mutate vuex store state outside mutation handlers`

I really need to fix this issue, and driving me crazy right now.

**Comment by unr** [comment] 2018-10-24 20:32
Hmm, I haven't run into that specific error with this setup @jjoao07 

Are you sure that it is being caused by the createPrivate call, and not another vuex call?

Otherwise.... Maybe it's where we return a promise, and `commit` inside that, that vuex doesn't like. 🤔

**Comment by jjoao07** [comment] 2018-10-24 20:40
Hi @unr , Yes I'm sure about it. the problem is with that commit,

If I comment the commit, the script run, but I don't have how to access  it from outside.

so not sure how I can access Echo instance, without committing or to run it without getting vuex error

**Comment by unr** [comment] 2018-10-24 20:53
Oh, I see what you're doing. 

You seem to call `this.$store.dispatch('echoModule/createPrivate')` directly, but what should happen is **you try to join a channel, and that creates the instance for you.**


In your version of the gist, you only have `connectToConversationChannel`, which uses the private instance.

In a perfect world, calling `this.$store.dispatch('echoModule/connectToConversationChannel')` create the instance, and then connect to it.

You should then have a method to leave those channels.


---


It sounds like you may be doing something like this, instead of the above.

1. create instance via `this.$store.dispatch('echoModule/createPrivate')`
2. try to join a channel via `this.$store.state.echoModule.instance.public()`

**Comment by jjoao07** [comment] 2018-10-24 21:03
@unr Okay thanks, will try out in the morning, and let u know. 

For now, I was just trying to see if I can listen to the event and console.log, so that I could move on and implements the leave and other stuff.

Perhaps is your events namespace located in Events dir like App\Events\EventsClass or something like App\Events\dir\EventClass,  because I'm also guessing to have some issues with namespacing, but I have tried to listen to it like below.

`
Echo.private('channel').
    .listen('EventClass', (e) =>{
    console.log(' I couldn't get nothing like this and moved on to namespace with . like below')
})
`


`
Echo.private('channel').
    .listen('.EventClass', (e) =>{
    console.log('Even this also didn'\t worj and tried last one')
})
`


`
Echo.private('channel').
    .listen('.App.Events.EventClass', (e) =>{
    console.log(' and without success')
})
`

**Comment by unr** [comment] 2018-10-24 21:08
Personally, my private channels are user specific. I access them like

```
state.instance.private(`User.${uuid}`)
    .notification((notification) => console.log(notification));
```

For my public channels,

```
state.instance.channel('live')
    .listen('MatchScoreChanged', notification => dispatch('handleMatchScoreChanged', notification));
```

(I'm not a pro with backend/laravel... I'm just a lowly frontend! Not sure on what/why you need to listen to something specific)

> In my example, `state.instance` == `Echo` in your example.

**Comment by jjoao07** [comment] 2018-10-25 22:03
Hi @unr I just fixed it. but I used it on my way not in your way. the main issue was the endpoint url
I was using it under API route which was wrong. below is a gist solution

https://gist.github.com/jjoao07/ca233477b495ed8188fb618823108624

Thanks, @unr for your help and feedback

**Comment by unr** [comment] 2018-10-25 22:43
Glad to see your problem solved @jjoao07 

And thanks for sharing your solution as well. :)

**Comment by driesvints** [comment] 2018-10-31 12:07
Going to close this as this discussion has gone off topic quite a bit.

**Closed by driesvints** 2018-10-31 12:07 UTC

**Comment by chrisijoyah** [comment] 2019-01-28 17:10
How do you obtain the bearer token ?

**Comment by albay13** [comment] 2019-07-10 01:55
Hey @jjoao07 you can check your BroadcastServiceProvider.php on App/Providers/BroadcastServiceProvider.php then change make your Broadcast::routes(['middleware' => ['auth:users']]) something like this. In my case, it works!

**Comment by rauschmerscen** [comment] 2019-07-27 11:00
Soultion to Common Problems faced by many users while setting up Laravel Echo
https://gist.github.com/rauschmerscen/2f2265976d59267f3bfccb339b27be44

**Comment by mengyang1229** [comment] 2021-09-03 09:34
Echo.connector.options.auth.headers.Authorization = 'Bearer token';
