### ISSUE TITLE
Redis keyPrefix Problem

### ISSUE THREAD

**Issue by canozgen9** [laravel/echo#232] opened 2019-05-24 03:37 UTC
- Echo Version: 1.5.3
- Laravel Version: 5.8.*
- PHP Version: 7.2.17
- NPM Version: 6.8.0
- Node Version: 8.10.8

### Description:
When Echo used with Redis, it produces keyPrefix to every channel you created. (which is by default "laravel_database_")

### Steps To Reproduce:
1-) Use Redis as Broadcast Driver and Queue Connection
```env
BROADCAST_DRIVER=redis
QUEUE_CONNECTION=redis
```
2-) Create any Event
```php
class UserRegistered implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public $user;

    public function __construct(User $user)
    {
        $this->user = $user;
    }

    public function broadcastOn()
    {
        return new PrivateChannel('test');
    }

    public function broadcastAs()
    {
        return 'user.registered';
    }

    public function broadcastWith()
    {
        return ['id' => $this->user->id];
    }
}
```
3-) Broadcast this event with Private Channel called 'test'
4-) Authorize this channel 
```php
Broadcast::channel('test', function ($user) {
    return $user;
});
```
5-) Initialize Echo in your js file
```js
import Echo from "laravel-echo"

window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: window.location.hostname + ':6001',
    authEndpoint: "/broadcasting/auth",
});
```
6-) Initialize your channel
```js
 Echo.private(`test`)
                .listen('.user.registered', function (e) {
                    console.log(e);
                });
```
7-) Send event
```php
event(new UserRegistered($user));
```
8-) See laravel-echo-server logs
```log
[6:13:51 AM] - W3drJJWfqL9OacTmAAAa authenticated for: private-test
[6:13:51 AM] - W3drJJWfqL9OacTmAAAa joined channel: private-test
Channel: foo_bar_database_private-test
Event: user.registered
```

My Redis keyPrefix is "foo_bar_database_", so the channel name that the event emitted is "foo_bar_database_private-test" but i am listening the channel "private-test". So Echo never gets the event.

I tried to delete "private-" prefixes from both php&js side but this time Echo not requiring to authenticate channel anymore since not see as private channel.

**Comment by canozgen9** [comment] 2019-05-24 04:34
It can be fixed by below steps.
1-) Remove all "'private-' + " prefixes in your compiled **Echo.js**
_This will make your channel name not being prefixed with "private-"._
2-) At the backend part, authorize your channels in **routes/channels.php** as follows
_Add your prefix to channel name._
 ```php
Broadcast::channel('foo_bar_database_private-test', function ($user) {
    return true;
});
```
3-) At the frontend part, register your channels as follows
_Add your prefix to channel name. Your channel name will not be prefixed with "private-"._
```js
Echo.private(`foo_bar_database_private-test`)
                .listen('.user.registered',function (e) {
                    console.log(e);
                });
```
4-) Broadcast event and see console output for laravel-echo-server
```log
[7:19:56 AM] - 5KykLGFS9kiYu8pFAAAF authenticated for: foo_bar_database_private-test
[7:19:56 AM] - 5KykLGFS9kiYu8pFAAAF joined channel: foo_bar_database_private-test
Channel: foo_bar_database_private-test
Event: user.registered
```
5-) As you can see, the channel names match. 

To solve this bug, **Private**("private-") and **Presence**("presence-") prefixes should not be mandatory.

**Comment by driesvints** [comment] 2019-05-27 14:10
Do you actually need the Redis prefix in this situation?

**Comment by AdSegura** [comment] 2019-05-27 16:38
Same problem here.

Echo.private will add a prefix **private-** to channel's name.

So Laravel adds **laravel_database_private-**_channel_ prefix and 

Echo.private(laravel_database_private-channel) will add another prefix like so:

**private-** laravel_database_private-channel

And Echo will not get the event never becouse it's listening on other channel.

**Comment by AdSegura** [comment] 2019-05-27 18:09
I was able to get it working:

In **config/database.php** disable prefix for redis.

Now i can do
```
 window.Echo.private('channel')
```

And in **routes/channels.php** 

```
Broadcast::channel('channel', function ($user) {
```

With **redis-cli monitor** :+1: 
```
1558979801.909666 [0 172.20.0.1:35198] "PUBLISH" **"private-channel"** "{\"event\":\"App\\\\Events\\\\PrivateMessage\",\"data\":{\"msg\":\"Hello\",\"user\":\"foo\",\"socket\":\"vDVEap6hCjgJ5OhtAAAB\"},\"socket\":\"vDVEap6hCjgJ5OhtAAAB\"}"
```

And Echo clients gets their message.

**Comment by canozgen9** [comment] 2019-05-28 04:51
> Do you actually need the Redis prefix in this situation?

Actually i do, because i have a server with multiple websites. The keys may conflict.

**Comment by driesvints** [comment] 2019-05-28 11:57
We probably don't want to fiddle too much with the internals with Echo. Is there some way we can strip the redis prefix again when fetching the events? Trying to think out load here.

**Comment by driesvints** [comment] 2019-06-03 07:06
Closing this since this is more of a framework issue than echo. Let's continue the discussion here: https://github.com/laravel/framework/issues/28701

**Closed by driesvints** 2019-06-03 07:06 UTC
Labels: needs more info

**Comment by thomaswardiii** [comment] 2019-10-21 22:01
I know this is closed but I disagree that this is a framework issue. The echo server should be configurable such that if there is a prefix it can be appended to the names of the keys. If this is how Laravel writes to redis, why should this not support that prefix?

It tends to default to `strtolower(Str::snake(config('app.name')))`

**Comment by eightyfive** [comment] 2020-01-26 04:33
This is definitely a `laravel/echo` issue IMHO. Backend behaves as expected: Sending namespaced events to the `laravel-echo-server`. It's up to the client to know what namespaced events it wants to listen to.

**Comment by eightyfive** [comment] 2020-01-26 04:40
@driesvints 
```js
const echo = new Echo({
  // ...
  keyPrefix: "laravel_database_"
});
```

What do you think?

**Comment by driesvints** [comment] 2020-01-27 10:45
@eightyfive laravel echo server has introduced a prefix by now: https://github.com/laravel/framework/issues/28701#issuecomment-557155843

**Comment by eightyfive** [comment] 2020-01-27 10:51
@driesvints Indeed and echo server does broadcast the event with the keyPrefix. So nothing wrong here.

Problem is echo Client no picking up that prefixed event: laravel_database_private-App\...

I’m pretty sure I am not mistaken cause when I remove the keyPrefix everywhere (Laravel & echo server), echo client works fine. So it’s pretty clear it does not listen to the keyPrefixed event name.

Let me know, thanks.

**Comment by driesvints** [comment] 2020-01-27 10:59
@eightyfive can you verify with laravel-echo-server that this never worked on their side and report back? Thanks!

**Comment by niocncn** [comment] 2020-02-02 17:57
same issue, keyPrefix in echo options needed =(

**Comment by eightyfive** [comment] 2020-02-12 09:04
Hey all,

This has been [fixed in `laravel/framework`](https://github.com/laravel/framework/pull/31261).

Turns out the bug was:

- Queue was properly listening to `laravel_database_*` prefixed events
- Redis broadcaster was ignoring  `database.redis.prefix` config option and broadcasting event *without* the prefix (this is the bug)
- Hence the queue was never receiving events broadcasted by Redis (name mismatch)

My bad pointing the problem might come from `laravel-echo` client.

**Comment by eightyfive** [comment] 2020-02-12 09:19
Hey all,

This has been [fixed in `laravel/framework`](https://github.com/laravel/framework/pull/31261).

Turns out the Redis Broadcaster was ignoring the `database.redis.prefix` config option.

My bad pointing out the problem might come from `laravel-echo` client.

**Comment by skeeith** [comment] 2020-02-23 04:21
@eightyfive Laravel still has this issue BTW. I just created a fresh Laravel app and tested this. confirmed it is still broadcasting the database redis prefix

**Comment by skeeith** [comment] 2020-02-23 04:37
@eightyfive I found the solution.

On your larave-echo-server.json file

```
"databaseConfig": {
	"redis": {
		"keyPrefix": "your_prefix_database_"
	},
}
```

**Comment by eightyfive** [comment] 2020-02-24 05:57
Problem was caused by [[6.x] Fix channel names when broadcasting via redis](https://github.com/laravel/framework/pull/31261), not by `databaseConfig.redis.keyPrefix` which is [well-documented](https://github.com/tlaverdure/laravel-echo-server#redis-1).

**Comment by omarjebari** [comment] 2020-03-23 04:10
As you're using Laravel just edit your .env file and set:

`REDIS_PREFIX=`

This will remove the 'foo_bar_database_' prefix from your channel names. Then make sure you've restarted your services.

**Comment by mengdodo** [comment] 2022-07-23 02:11
`REDIS_PREFIX ` can not be removed in my project

so

```
    public function broadcastOn()
    {
        return new PrivateChannel('doctor.qa.user_1');
    }
```

```
window.Echo.channel('nongji:private-doctor.qa.user_1')
    .listen('OrderMessage', e=>{
        console.log(e
    })
```
`nongji`  is REDIS_PREFIX variable in my project 😄
