### ISSUE TITLE
pusher - Connection interrupted when reloading page in chrome

### ISSUE THREAD

**Issue by vesper8** [laravel/echo#122] opened 2017-05-08 04:04 UTC
Not sure if this is the right place to write this issue.

Using Laravel + Vue + Pusher all the latest versions. It all works great and on first load there are no warnings in my Chrome console but then every time I reload the page (my page is not an SPA) it throws this warning:

```
Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":1006,"message":"Connection interrupted (0)"}}}
```

This also happens if I just click a link to change pages

I know it's just a warning but is it supposed to be there and can I quiet it? I like to keep my console clear

**Comment by umakant-sutar** [comment] 2017-05-16 12:30
Any resolvement on this one?=

**Comment by thecodedad** [comment] 2017-06-13 17:15
I seem to be having the same issue [ with the same setup ] and I've been unable to identify / resolve it.

**Comment by fendiseptiawan0709** [comment] 2017-06-22 05:57
I'm also facing same problem...
Please help me to resolve this issue...
![pusher](https://user-images.githubusercontent.com/16249274/27419312-619709fa-574a-11e7-8c58-3f31a1c511f7.png)

**Comment by sigfriedseldeslachts** [comment] 2017-07-03 15:19
Same issue here

![https://puu.sh/wABfE/14de8cccbf.png](https://puu.sh/wABfE/14de8cccbf.png)

**Comment by ruman63** [comment] 2017-07-15 09:28
I am also facing the same issue. Couldn't Identify the problem.

**Comment by spikefin-goby** [comment] 2017-07-20 05:04
Sorry for my poor English.

Probably caused by LocalStrage named "pusherTransportEncrypted" or "pusherTransportUnencrypted".

In my case, after deleting localstrage, no warning is output.

https://github.com/pusher/pusher-js/blob/0ef56995ed9605b79ba4b22d1a13c84652d47793/src/core/strategies/cached_strategy.ts#L92

**Comment by jhon-andrew** [comment] 2017-08-11 01:25
Are there confirmed solutions for this already? I'm also facing the same issue.

**Comment by gryshkoevgeniy** [comment] 2017-08-17 10:41
Today the same problem has appeared. Yesterday, this error was not yet.

//in console
Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":1006,"message":"Connection interrupted (0)"}}}

// in network tab
Request URL:https://sock21-eu.pusher.com/pusher/app/6f8a91f07e76fe56ae37/79/lli5nep9/xhr_send?t=1502966355399&n=10
Request Method:OPTIONS
Status Code:204 No Content
Remote Address:34.252.145.15:443
Referrer Policy:no-referrer-when-downgrade

Request URL:https://sock21-eu.pusher.com/pusher/app/6f8a91f07e76fe56ae37/79/lli5nep9/xhr_send?t=1502966355399&n=10
Request Method:POST
Status Code:204 No Content
Remote Address:34.252.145.15:443
Referrer Policy:no-referrer-when-downgrade

**Comment by edgarnadal** [comment] 2017-08-23 21:59
@spikefin-goby solution solved my problem.

**Comment by driesvints** [comment] 2018-10-30 17:52
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Closed by driesvints** 2018-10-30 17:52 UTC
