### ISSUE TITLE
Event not being triggered by Pusher.

### ISSUE THREAD

**Issue by Kreshnik** [laravel/echo#73] opened 2016-12-21 01:36 UTC
Hi,

I think the event listener for private channels is not functioning correctly. I have followed the documentation so far, but Pusher is not triggering the event listener. In pusher under the debug console, I can see that the data is present, which can be seen in the attached image.

I also am posting below the code the I am using, in case the mistake is on my side (which I don't hope).

```
<?php

namespace App\Events\Chat;

use Illuminate\Broadcasting\Channel;
use Illuminate\Queue\SerializesModels;
use Illuminate\Broadcasting\PrivateChannel;
use Illuminate\Broadcasting\InteractsWithSockets;
use Illuminate\Contracts\Broadcasting\ShouldBroadcast;

class UserSendChatMessage implements ShouldBroadcast
{
    use SerializesModels, InteractsWithSockets;
    
    public $id;


    /**
     * UserSendChatMessage constructor.
     * @param $user
     * @param $message
     */
    public function __construct($id)
    {
        $this->id = $id
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return Channel|array
     */
    public function broadcastOn()
    {
        return new PrivateChannel("conversation.{$this->id}");
    }

}
```

```
Echo.private('conversation.' + this.uniqueConversationId)
                        .listen('.App.Events.Chat.UserSendChatMessage', function (event) {
                            alert('here...');
                            console.log(event);
                        });
```
```
 Broadcast::channel('conversation.*', function ($user, $uniqueId) {
            // Security: not secure, yet.
            return true;
        });
```

<img width="836" alt="screen shot 2016-12-21 at 2 31 51 am" src="https://cloud.githubusercontent.com/assets/1788349/21374266/d0d38b6e-c725-11e6-805d-b3f4f8f976c5.png">

**Comment by JBlaak** [comment] 2016-12-27 16:26
I can reproduce this, tried the pusher-js library on `4.0.0` and `3.2.4` to make sure it wasn't a dependency problem.

**Comment by JBlaak** [comment] 2016-12-28 13:33
For me a dive into how `listen` differs from `on` provided my solution, it will first pass the event through the event formatter, which will add a namespace. https://github.com/laravel/echo/blob/master/src/channel/pusher-channel.ts#L89

**Comment by Kreshnik** [comment] 2016-12-31 13:10
Thanks @JBlaak your answer was of great help.

**Comment by morloderex** [comment] 2017-01-07 17:35
Are you sure you are on the correct cluster? :) in both laravel-echo and your laravel application.

**Comment by Kreshnik** [comment] 2017-01-07 17:52
@morloderex yes, I have set for both the 'eu' cluster. To provide a little more information, I listening from within vuejs mounted event after the $nextTick event. See source code below;

```
mounted() {
            this.$nextTick(function () {

                Event.listen('conversation:load', function (uniqueConversationId) {
                    
                        Echo.private('conversation.' + this.uniqueConversationId)
                        .listen('.App.Events.Chat.UserSendChatMessage', function (event) {
                            console.log(event);
                        });

                }.bind(this));

            });
}
```

**Comment by maxpaynestory** [comment] 2017-06-01 13:10
Are you sure your Vue event 'conversation:load' is called and do you have access to Echo instance inside event. Have you created echo instance using.

```Javascript
window.Echo = new Echo();
```

There is a dot(.) at start of your 'App.Events.Chat.UserSendChatMessage' is that intentional?

**Comment by morloderex** [comment] 2017-06-01 23:16
Can you see the event name on the pusher debug console? 
Maybe your name is incorrect as @maxpaynestory suggests?

**Comment by zedentox** [comment] 2017-06-11 21:28
There is a similar bug concerning dots in events names #119 
I think it's the same problem.

**Comment by johnpozy** [comment] 2017-06-27 17:02
Avoid using dot notation in your event name for now.

`<?php

namespace App\Events\Web\Backend\Plan;

use App\Models\Plan;

use Illuminate\Broadcasting\Channel;
use Illuminate\Queue\SerializesModels;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Broadcasting\InteractsWithSockets;
use Illuminate\Contracts\Broadcasting\ShouldBroadcast;

class TestEvent implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    /**
     * Plan
     *
     * @var object $plan
     */
    public $plan;

    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct(Plan $plan)
    {
        $this->plan = $plan;
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return Channel|array
     */
    public function broadcastOn()
    {
        return new Channel('test');
    }

    /**
     * The event's broadcast name.
     *
     * @return string
     */
    public function broadcastAs()
    {
        return 'test';
    }
}`

**Comment by johnpozy** [comment] 2017-06-27 17:13
Avoid using the dots for your event name. Try using something like `my-event-name` or `my:event:name`. You could rename the event name via `broadcastAs` function as per [documentation](https://laravel.com/docs/5.4/broadcasting#broadcast-name). Then simply listen to the event like the below code
```
window.Echo.channel('test').listen('.my-event-name', (event) => {
    console.log(event)
})
```
The leading `.` is to instruct Echo to not prepend the application's namespace to the event. Hope it will help someone 😄

**Comment by driesvints** [comment] 2018-10-31 11:33
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Closed by driesvints** 2018-10-31 11:33 UTC
