### ISSUE TITLE
Function for when the user disconnects from the channel

### ISSUE THREAD

**Issue by dpollard** [laravel/echo#67] opened 2016-12-01 21:12 UTC
So currently, the way echo is set up, the following will allow me to react when a user disconnects:

```javascript
 Echo.here('my-channel')
 .leaving((d) => {
        // a user disconnected
 	console.log(d);
 });
```

Is there any possible way that I could also receive notice when *I* am leaving the channel (for online status)? (I being the person who was visiting the application and decided to disconnect from the channel)

Currently through echo, this is not possible but am wondering what this would require to implement?

**Comment by morloderex** [comment] 2016-12-01 21:31
It is already implemented. 
It's called leaving. You could also listen to the here callback which will execute whenever a person leaves or joins the channel.. :)

**Comment by dpollard** [comment] 2016-12-01 21:45
Whoops, I forgot to change `here` to `leaving` - I am not looking for the `leaving()` implementation as it only notifies the other users that a user has left - I need it to notify the server that the user who left is no longer active.

**Comment by dpollard** [comment] 2016-12-01 23:17
Re wrote the code because it didn't make sense but yeah.  See original comment.

**Comment by akizor** [comment] 2018-08-09 07:38
Might wanna look at this [stackoverflow question](https://stackoverflow.com/a/47648234/925058)

**Comment by d-pollard** [comment] 2018-08-09 08:05
@akizor - the problem is getting echo to broadcast an event to the server, so none of the aforementioned projects would work, unfortunately. I ended up just rolling my own implementation based on echo-server (which I have scaled out on AWS ELB).

**Comment by driesvints** [comment] 2018-10-31 11:51
Is this still a problem? If so I think we'd be open to PRs which would solve this somehow.

**Comment by ricardogobbosouza** [comment] 2019-09-14 11:01
@dpollard see https://pusher.com/tutorials/online-presence-laravel
Can close this?

**Comment by d-pollard** [comment] 2019-09-16 14:46
@ricardogobbosouza sure, you can close this

**Comment by ricardogobbosouza** [comment] 2019-09-16 19:14
@taylorotwell can close?

**Closed** 2019-09-23 14:07 UTC
Labels: enhancement
